Use Alpine as base Docker image and bump dependencies
eliksir/screenie-server pull request #14
Opened 2019-10-30 13:14 UTC by stianpr

Should work like before and we should see an overall decrease in image size by 50%.

2019-10-30 13:37 UTC, asteinlein approved these changes

2019-10-31 09:20 UTC, fdanielsen requested changes
Some minor feedback, but would also be good to look into aligning Chromium version in Docker with the default version in Puppeteer 2.0.0.

2019-10-31 09:20 UTC, fdanielsen commented on CHANGES.md
> +* by over 50%.
"by over 50%" shouldn't be its own bullet point ;)

2019-10-31 09:20 UTC, fdanielsen commented on package.json
> +    "puppeteer": "2.00.0",
Version should be "2.0.0".

2019-10-31 09:20 UTC, fdanielsen commented on Dockerfile
> +# Installs make, g++, python and Chromium (77) packages.
Can we align with Puppeteer 2.0.0 which comes with Chromium 79.0.3942.0 by default?

2019-10-31 09:38 UTC, stianpr commented on Dockerfile
> +# Installs make, g++, python and Chromium (77) packages.
No, latest alpine 3.10 has only Chromium 77 available, but it does work with Puppeteer 2.0. [Even alpine edge has only v77](https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium).

2019-10-31 09:38 UTC, stianpr commented on package.json
> +    "puppeteer": "2.00.0",
a true.

2019-10-31 10:40 UTC, fdanielsen approved these changes

2019-10-31 10:40 UTC, fdanielsen commented on CHANGES.md
> +* Use Alpine as base docker image
"Docker"

2019-10-31 10:40 UTC, fdanielsen commented on package.json
> +    "node": ">= 8.0.0"
I think we just require node 7.6.0 now given the Koa update. It's puppeteer 2.0.0 which requires 8.0.0.

2019-10-31 11:55 UTC, merged