Add certificate update to Dockerfile
eliksir/screenie-server pull request #4
Opened 2017-07-05 18:56 UTC by anfedorov

Fixes #3 using instructions from this SO answer:
https://stackoverflow.com/a/33353762/8016079

2017-07-05 20:00 UTC, anfedorov commented
if you'd like to keep the change even more minimal, this works, as well: 
```FROM node:7.7.2-alpine

ENV SCREENIE_VERSION=1.1.0

RUN apk add --no-cache fontconfig curl ca-certificates \
    && curl -Ls "https://github.com/dustinblackman/phantomized/releases/download/2.1.1/dockerized-phantomjs.tar.gz" | tar xz -C / \
    && npm install -g screenie-server@$SCREENIE_VERSION \
    && apk del curl \
    && rm -rf /tmp/*

EXPOSE 3000

CMD update-ca-certificates && /usr/local/bin/screenie
```

2017-07-06 10:37 UTC, asteinlein requested changes
Thanks for the PR! Could you try the following and see if it still fixes your case:

Just add ca-certificates to the existing `apk add` line (instead of adding a separate RUN), and add a new line that runs `update-ca-certificates` into the existing RUN? Seems a bit overkill to run that command on every start of a container?

2017-07-06 10:37 UTC, asteinlein commented on Dockerfile
> +    apk add curl ca-certificates
What's curl needed for? The SO thread you linked to didn't mention that.

2017-07-06 10:39 UTC, asteinlein commented
Basically, I like your minimal version better. Just wondering if we can run the `update-ca-certificates` command during build, instead of when starting the server.

2017-07-06 17:01 UTC, anfedorov reviewed
so certs can change at any time, and for some cases, you really want revoked certs to make it back to your images *before* they restart, and definitely before you re-build from your Dockerfile (which, if I understand correctly, is ideally never?).

happy to move it, but I'm pretty sure you'll run into the same case at some point unless regularly re-building the image from your Dockerfile is part of your process.

2017-07-06 17:01 UTC, anfedorov commented on Dockerfile
> +    apk add curl ca-certificates
oops, that's from when I first tried adding it below. can take it out here.

2017-07-07 10:41 UTC, asteinlein approved these changes

2017-07-07 10:42 UTC, merged

2017-07-07 10:45 UTC, asteinlein commented
Thanks for the patch and the update! A new Docker image built from this is pushed to the Docker hub. :)